# fly.toml app configuration file generated for v6-weathered-firefly-345 on 2025-09-13T23:01:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'v6-weathered-firefly-345'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3500
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  VALIDATOR_HEAP='512M'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
