# fly.toml app configuration file generated for kiln on 2025-09-13T21:08:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kiln'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3500
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
